CREATE TABLE [dbo].[T3] (
    [Key]   INT IDENTITY (1, 1) NOT NULL,
    [T1Key] INT NOT NULL,
    PRIMARY KEY CLUSTERED ([Key] ASC),
    CONSTRAINT [FK_T3_T1] FOREIGN KEY ([T1Key]) REFERENCES [dbo].[T1] ([Key])
);

